version: "3"

services:
  db_docker:
    container_name: database
    image: library/postgres
    env_file:
      - ".env"
    environment:
      #  Данные для создания пользователя и БД
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      # сохраняем данные из БД контейнера на сервере в ./postgres-data
      - ${PG_DB_DUMP}/udemy_final_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - botnet
    restart: always

  tgbot:
    container_name: bot
    build:
      # берём Dockerfile для бота
      context: .
    env_file:
      - ".env"
    command: python bot.py
    # Только на период разработки. Потом убрать.
    volumes:
      - .:/home/bot
    networks:
      - botnet
    restart: always
    depends_on:
      - db_docker

networks:
  botnet:
    driver: bridge

volumes:
  udemy_final_pgdata: